### ISSUE TITLE
Question: How to parse recursive paths?

### ISSUE THREAD

**Issue by arcmode** [evancz/url-parser#12]
Hi, thanks for making Elm, it's great!.

Well, I have this type for pages:

```
  type Page
      = CollectionPage String (Maybe Page)
      | ItemPage  Int (Maybe Page)
```

And I'm trying to parse paths like this:

```
  /users/5/friends/9 
```

Into this:

```
  page =
      CollectionPage "users"
          (Just
              (ItemPage 5
                  (Just
                      (CollectionPage "friends"
                          (Just (ItemPage 9 Nothing))
                      )
                  )
              )
          )
```

So far I have managed to parse only explicit paths using `format`, but I want a general parser for arbitrary recursive paths. Is there an idiomatic way to achieve this recursive parsing using `format` or do you think I need to make something with `custom` or anything else?

**Comment by evancz** [comment]
Thanks :) Before answering the general question, I'd like to know more about your scenario. Are you saying that the following path is valid for you?

```
/users/5/users/5/users/5/users/5/users/5/
```

Can you be more explicit about the paths that are valid? What exactly are you trying to do?

(Also, these questions are typically better for the Elm slack channel or for elm-discuss.)

**Comment by arcmode** [comment]
Hello, thanks for answering.

Any path formed by strings and numbers would be valid initially. I just want to represent paths with a recursive type because I want to play with a recursive `viewPage : Page -> Html msg` where each _node_ decides how to treat its child _node_ and so on.

I think I probably will have to change the type `Page` to be able to pattern-match everything safely but the core of my question is _how can I parse recursively using this library in order to produce recursive values?_. My best idea right now is to use _custom_ directly instead of _format_.

Sorry for posting a non-issue by the way, I will bring this into slack and or elm-discuss. Do you mind if I share the link to this issue with more people or you prefer to close it?

**Comment by evancz** [comment]
You cannot do it with the current API. I would not want to support that in this library unless we had a good concrete scenario that will come up in practice often. That said, you can always parse things from the `Location` yourself, so nothing is stopping you from handling "recursive paths".

It's fine to link here, but I think it'd be better to continue discussion in another place. If that turns into a specific example that is representative of general use, open a new issue about that.
