### ISSUE TITLE
parseHash + stringParam not working

### ISSUE THREAD

**Issue by littleStudent** [evancz/url-parser#20]
I am having problems with parseHash and stringParam together.
I checked out the example app and changed the following.

1. `parsePath` -> `parseHash` in line 30 + line 72
2. changed line 94 to `, ul [] (List.map viewLink [ "/#/", "/#/blog/", "/#/blog/42", "/#/blog/37", "/#/blog/?search=cats" ])`

The first 3 paths work without any problems. But `/#/blog/?search=cats` results in "Invalid URL".
Am I missing something or is it a bug?

here is the fork with these minimal changes https://github.com/littleStudent/url-parser

ADD:
it seems like `document.location.search` is empty when using Hash. So is there even a way to use query strings?

**Comment by sporto** [comment]
Should be `?search=cats#/blog/`. The query needs to go first.
