### ISSUE TITLE
Parsing empty hash doesn't work

### ISSUE THREAD

**Issue by rogeriochaves** [evancz/url-parser#21]
When I have a path that responds to empty `""`, having the url at `#` does not get parsed correctly. Example:

```elm
pageParser : Parser (Page -> a) a
pageParser =
    oneOf
        [ map IndexRoute (s "")
        , map SearchRoute (s "search")
        ]


-- this doesn't work!
parseHash pageParser { hash = "", host = "", hostname = "", href = "", origin = "", password = "", pathname = "", port_ = "", protocol = "", search = "", username = "" }

-- this neither (but it is not the usual case, location hash is never #)
parseHash pageParser { hash = "#", host = "", hostname = "", href = "", origin = "", password = "", pathname = "", port_ = "", protocol = "", search = "", username = "" }

-- this does, returns SearchRoute
parseHash pageParser { hash = "#search", host = "", hostname = "", href = "", origin = "", password = "", pathname = "", port_ = "", protocol = "", search = "", username = "" }
```

(elm 0.18, url-parser 2.0.1)

**Comment by amilner42** [comment]
Ya this got me as well, exactly as described by @rogeriochaves, we should try and fix this ASAP cause it'll throw off beginners and I'd imagine it's not a complex fix (extra case needed to check a parser where the location hash is `""` or `"#"`)

**Comment by amilner42** [comment]
It's worth adding that it worked in the previous version of UrlParser, so it's definitely worth mentioning so when everyone updates to 0.18 they see that you have to use `top` (thanks to Elm slack was just informed of this).

Perhaps an extra sentence on the doc for `top` showing that you can use it for the empty case

**Comment by evancz** [comment]
The expression `s "cat" </> s "" </> int` will look for a segment like `cat//4`. In other words, it is looking for a segment *that exists* that has nothing. Something like `//`. So I suspect you want `top` instead. I don't really see what `s ""` should mean instead of the literal interpretation.
