### ISSUE TITLE
Learning Elm, and trying to read this source. What *is* a Parser!?

### ISSUE THREAD

**Issue by colinta** [evancz/url-parser#28]
I have not been able to figure out how to read this type definition:

```elm
type Parser a b =
  Parser (State a -> List (State b))
```

Can you explain what the `Parser` type is?  Sorry to bother you with this, hopefully it's easy, but nothing I've read in the docs about types mentions this syntax, or why you need it / use it (`type A b c = A (... b ... c)`)

**Comment by evancz** [comment]
You can definitely get some help with this through a community forum: http://elm-lang.org/community
