### ISSUE TITLE
Example for `parse` is not working 

### ISSUE THREAD

**Issue by domenkozar** [evancz/url-parser#3]
As written:

```
> parse (,) (s "blog" </> int </> string) "/blog/42/cat-herding-techniques"
Err "Wanted /blog but got //blog/42/cat-herding-techniques"
    : Result.Result String ( Int, String )
```

Works without the slash:

```
> parse (,) (s "blog" </> int </> string) "blog/42/cat-herding-techniques"
Ok (42,"cat-herding-techniques") : Result.Result String ( Int, String )
```

cc @evancz

**Comment by evancz** [comment]
Can you make a PR that removes the slash from the example?

**Comment by evancz** [comment]
I fixed it.

**Comment by paulstatezny** [comment]
Thanks for writing this! Question related to this issue.

Does the library assume all paths given will omit the leading slash? According to this discussion (and behavior of the library) it seems so. But this is quite unclear according to the README:

[Snippet below, emphasis mine]

---

Here is a parser that handles URLs like **`/blog/42/whale-songs`**...

``` elm
blog : Parser (Int -> String -> a) a
blog =
  s "blog" </> int </> string
```

---

(Also see the only other example in the README.) Any clarity would be greatly appreciated. This really tripped me up. Thanks!
