### ISSUE TITLE
Is there way to get tail of the URL ?

### ISSUE THREAD

**Issue by deem0n** [evancz/url-parser#34]
Hello,

I am a newbie and want to integrate auth phase into my first SPA. My idea is to prefix normal URL with `#auth/` so I can send user to the correct page after successfull login.

Example:

1. User navigates to `#/items/123`
2. As result of data fetch request server send back 401 status, so I can know that I need to show login page
3. I redirect to `#/auth/items/123` somehow and display a login page there
4. User provides correct login and password and I just want to redirect at `#/items/123` at this stage

Something like `tail` would help me a lot:
```
 parseHash (s "auth" </> tail ) {  hash = "#/auth/items/123", host = "", hostname = "", href ="", origin = "", password="",pathname="", port_="", protocol="", search="", username="" }

Just "items/123" : Maybe.Maybe String
```

Or is there a better way to do auth redirects ?
Thanks!

**Comment by evancz** [comment]
I am tracking this feature request in #40. I'd like to get a broader understanding of all the usage scenarios before making the choice.
