### ISSUE TITLE
Support query params with no values.

### ISSUE THREAD

**Issue by amilner42** [evancz/url-parser#36]
For the use-case where you want a query param but it carries no connected value. You can see [here](http://stackoverflow.com/questions/4557387/is-a-url-query-parameter-valid-if-it-has-no-value) (or jump directly to the [RFC here](https://tools.ietf.org/html/rfc3986#section-3.4)) that this is fully valid.

It just seems silly to do something like `Maybe ()` when you really just want a boolean.

**Comment by evancz** [comment]
Tracking in #41. Can you provide an example of exactly the URL you want to parse and why you want to do that? That would help me understand your goals with this request better.

**Comment by NeverwinterMoon** [comment]
@evancz I am also in dire need of the same functionality. Our use case is this, we have "f" (as in first time) parameter in URL when a customer opens a page after purchase (the page is sort of a fancy receipt). Based on that, we show some banner. The same link can be opened from, say, email and it doesn't have the "f" parameter, so we don't show that same banner. We could have of course had "f=true", but we knew that parameter without a value is considered valid, and it was much shorter, so for us the presence of "f" means "f=true" and the absence is "f=false".

**Comment by amilner42** [comment]
@evancz My apologies, I meant to respond sooner but I've been really busy.

I have a roughly similar situation to @NeverwinterMoon, also wanting parser support for a query param with no connected value (which is valid).
