### ISSUE TITLE
Get "the rest" of a URL

### ISSUE THREAD

**Issue by slashmili** [evancz/url-parser#46]
I'm adding this issue in order to add another use case of #40.

I'm working on an app that shows the files inside a git repository.

The link is would be something like this.

```
http://localhost:4000/#/slashmili/my-app/tree/master/src
```

and if someone click on a file on above page would go to 

```
http://localhost:4000/#/slashmili/my-app/tree/master/src/myfile.ex
```

This is the route I use 
```
ShowRepositoryTree String String (List String)
```

**Comment by evancz** [comment]
Tracking in #40. Thank you for the usage example!
