### ISSUE TITLE
Doc typo: missing a `s` in the `oneOf` example

### ISSUE THREAD

**Issue by magopian** [evancz/url-parser#47]
I believe the line at https://github.com/evancz/url-parser/blob/7c67e7f95a49c9a0e4b51b91d4fd05169dacc680/src/UrlParser.elm#L208

Should instead read

```Elm
, map Comment (s "user" </> string </> s "comments" </> int)
```

(see the additional `s` before `comments`).

**Comment by evancz** [comment]
Looks like it is missing an `s`! I have since redone the examples for the next iteration of this API and that mistake did not make it into the new `oneOf` docs.
