### ISSUE TITLE
First argument to `custom` is not used any more. Caused confusion among some users.

### ISSUE THREAD

**Issue by wking-io** [evancz/url-parser#51]
If you have time in your crazy schedule the first argument to `custom` which was originally used for error messages is no longer used and caused some confusion in the #beginner thread on Slack. Just wanted to point that out in case you had time to remove it! 

Have a good day!

**Comment by evancz** [comment]
Thanks for the report! The new API lives at https://github.com/elm-lang/url. Do you mind seeing if it is still there in that API? If so, can you open an issue there with an example of the issue? (The new version will come out with 0.19)
