### ISSUE TITLE
cannot download ktonon fork

### ISSUE THREAD

**Issue by gaul** [evancz/url-parser#56]
@ktonon I can no longer download your fork:

```
Warning: Unable to complete missing packages check - Command failed: elm-package install --yes
Error: The following HTTP request failed.
<http://package.elm-lang.org/description?elm-package-version=0.18&name=ktonon%2Furl-parser&version=2.0.2>

That library and version is not registered.
```

http://package.elm-lang.org/packages/ktonon/url-parser/latest reports:

```
problem with parameter 'version': Must have format MAJOR.MINOR.PATCH (e.g. 1.0.2)
```

**Comment by evancz** [comment]
I think this is based on some cleanup I was doing of packages that seemed to have published tags that were deleted later. I assumed that meant the libraries were in disrepair, but I guess that is not the case.

@ktonon, which versions are intended to work? I think the easiest path may be to republish them in the same order as before. Sorry for the trouble on this!

**Comment by evancz** [comment]
Never mind, I just reverted what I did. It should be fine now.
